services:
  cassandra:
    image: pmcfadin/cassandra-accord
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=AccordCluster
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/opt/cassandra/data
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra_data:
    driver: local